site_name: s-tanaka-test
theme:
  name: material
  palette:
    primary: teal
plugins:
  search:
    lang: 'ja'
extra:
  generator: false
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      pygments_style: monokai
      linenums: true